config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  resources :consumers#, only: [:new, :create, :show]

  resources :donors#, only: [:new, :create, :show]

  resources :contacts

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members
  resources :welcomes, only: [:index]

  root 'welcomes#index'

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	validates :name, :email, :cell, :donated_date, :subject, :presence => true
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_member!
  # GET /consumers
  # GET /consumers.json
  def index
    @consumers = Consumer.all
  end

  # GET /consumers/1
  # GET /consumers/1.json
  def show
  end

  # GET /consumers/new
  def new
    @consumer = Consumer.new
  end

  # GET /consumers/1/edit
  def edit
  end

  # POST /consumers
  # POST /consumers.json
  def create
    @consumer = Consumer.new(consumer_params)

    respond_to do |format|
      if @consumer.save
        format.html { redirect_to @consumer, notice: 'Consumer was successfully created.' }
        format.json { render :show, status: :created, location: @consumer }
      else
        format.html { render :new }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumers/1
  # PATCH/PUT /consumers/1.json
  def update
    respond_to do |format|
      if @consumer.update(consumer_params)
        format.html { redirect_to @consumer, notice: 'Consumer was successfully updated.' }
        format.json { render :show, status: :ok, location: @consumer }
      else
        format.html { render :edit }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumers/1
  # DELETE /consumers/1.json
  def destroy
    @consumer.destroy
    respond_to do |format|
      format.html { redirect_to consumers_url, notice: 'Consumer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumer_params
      params.require(:consumer).permit(:name, :gender, :email, :cell, :donated_date, :subject)
    end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/views/consumers/_form.html.erb
<%= semantic_form_for @consumer do |f| %>
  <%= f.inputs do %>
    <%= f.input :name, :input_html => { :size => 20 } %>
    <%= f.input :gender, :as => :radio, :collection => [:Male, :Female] %>
    <%= f.input :email, :input_html => { :size => 20 } %>
    <%= f.input :cell, :input_html => { :size => 20 }%>
    <%= f.input :donated_date, :input_html => { :size => 20 } %>
    <%= f.input :subject, :input_html => { :class => 'autogrow', :rows => 20, :cols => 18, :maxlength => 10000  } %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/consumers/edit.html.erb
<h1>Editing consumer</h1>

<%= render 'form' %>

<%#= link_to 'Show', @consumer %> |
<%#= link_to 'Back', consumers_path %>

app/views/consumers/index.html.erb
<h1>Listing consumers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Cell</th>
      <th>Donated date</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consumers.each do |consumer| %>
      <tr>
        <td><%= consumer.name %></td>
        <td><%= consumer.gender %></td>
        <td><%= consumer.email %></td>
        <td><%= consumer.cell %></td>
        <td><%= consumer.donated_date %></td>
        <td><%= consumer.subject %></td>
        <td><%= link_to 'Show', consumer %></td>
        <td><%= link_to 'Edit', edit_consumer_path(consumer) %></td>
        <td><%= link_to 'Destroy', consumer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Consumer', new_consumer_path %>

app/views/consumers/new.html.erb
<h3>New consumer</h3>

<%= render 'form' %>

<%#= link_to 'Back', consumers_path %>

app/views/consumers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @consumer.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @consumer.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @consumer.email %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @consumer.cell %>
</p>

<p>
  <strong>Donated date:</strong>
  <%= @consumer.donated_date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @consumer.subject %>
</p>

<%#= link_to 'Edit', edit_consumer_path(@consumer) %> |
<%#= link_to 'Back', consumers_path %>