config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  resources :consumers#, only: [:new, :create, :show]

  resources :donors#, only: [:new, :create, :show]

  resources :contacts

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members
  resources :welcomes, only: [:index]

  root 'welcomes#index'

end

app/models/donor.rb
class Donor < ActiveRecord::Base
	validates :name, :email, :cell, :donated_date, :subject, :presence => true
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_member!#, only: [:new, :create, :show]
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:name, :gender, :email, :cell, :donated_date, :subject)
    end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= semantic_form_for @donor do |f| %>
  <%= f.inputs do %>
    <%= f.input :name, :input_html => { :size => 20 } %>
    <%= f.input :gender, :as => :radio, :collection => [:Male, :Female] %>
    <%= f.input :email, :input_html => { :size => 20 } %>
    <%= f.input :cell, :input_html => { :size => 20 }%>
    <%= f.input :donated_date, :input_html => { :size => 20 } %>
    <%= f.input :subject, :input_html => { :class => 'autogrow', :rows => 20, :cols => 18, :maxlength => 10000  } %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%#= link_to 'Show', @donor %> |
<%#= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h1>Listing donors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Cell</th>
      <th>Donated date</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donors.each do |donor| %>
      <tr>
        <td><%= donor.name %></td>
        <td><%= donor.gender %></td>
        <td><%= donor.email %></td>
        <td><%= donor.cell %></td>
        <td><%= donor.donated_date %></td>
        <td><%= donor.subject %></td>
        <td><%= link_to 'Show', donor %></td>
        <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
        <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h3>New donor</h3>

<%= render 'form' %>

<%#= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donor.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @donor.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donor.email %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @donor.cell %>
</p>

<p>
  <strong>Donated date:</strong>
  <%= @donor.donated_date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @donor.subject %>
</p>

<%#= link_to 'Edit', edit_donor_path(@donor) %> |
<%#= link_to 'Back', donors_path %>