config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  resources :consumers#, only: [:new, :create, :show]

  resources :donors#, only: [:new, :create, :show]

  resources :contacts

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members
  resources :welcomes, only: [:index]

  root 'welcomes#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
end

app/controllers/stocks_controller.rb
class StocksController < InheritedResources::Base
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= semantic_form_for @stock do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :qty %>
    <%= f.input :expire_date %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Qty</th>
      <th>Expire date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.qty %></td>
        <td><%= stock.expire_date %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @stock.qty %>
</p>

<p>
  <strong>Expire date:</strong>
  <%= @stock.expire_date %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>